#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
qspi-configurator capsense-configurator capsense-tuner config_usbdev usbdev-configurator config device-configurator seglcd-configurator bsp-assistant smartio-configurator modlibs library-manager dfuh-tool config_ezpd ez-pd-configurator edge-protect-configurator :
	make -C proj_cm33_ns $@

config_lin lin-configurator config_bt bt-configurator secure-policy-configurator :
	$(error $@ configurator cannot be executed at the application level. Run this command from the desired project directory.)

.PHONY: qspi-configurator capsense-configurator capsense-tuner config_usbdev usbdev-configurator config_lin lin-configurator config device-configurator seglcd-configurator config_bt bt-configurator bsp-assistant smartio-configurator modlibs library-manager dfuh-tool config_ezpd ez-pd-configurator secure-policy-configurator edge-protect-configurator
